MVCFilmes/Models/ErrorViewModel.cs
namespace MVCFilmes.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCFilmes/Models/Filmes.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVCFilmes.Models
{
    public class Filmes
    {

         public int ID { get; set; }

        [MaxLength(100)]
        [Required(ErrorMessage = "Esse campo é obrigatorio")]
        public  string Titulo { get; set; } = string.Empty;

        [Required(ErrorMessage = "Esse campo é obrigatorio")]
        [Display(Name = "Data de Lançamento")]
        [DataType(DataType.Date)]
        public DateTime DataLancamento { get; set; }


        [
            Required(ErrorMessage = "Esse campo é obrigatorio"),
            StringLength(10),
            RegularExpression(@"^[A-z]+[a-zA-Z]*$", ErrorMessage = "Dados inválidos")

        ]
        public string Genero { get; set; } = string.Empty;


        [Required(ErrorMessage = "Esse campo é obrigatorio")]
        [Display(Name = "Preço")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Preco { get; set; }

        [Range(0,5, ErrorMessage = "Somente valores de 0 a 5")]
        public  int? Pontos { get; set; }
    }
}

MVCFilmes/Models/FilmesViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MVCFilmes.Models
{
    public class FilmesViewModel
    {

        public List<Filmes> ? Filmes{ get; set;  }
        public SelectList ? Generos { get; set; }
        public string ? Genero { get; set; }
        public string ? Texto { get; set; }
    }
}

MVCFilmes/Controllers/FilmeAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCFilmes.Data;
using MVCFilmes.Models;

namespace MVCFilmes.Controllers
{
    public class FilmeAController : Controller
    {
        private readonly MVCFilmesContext _context;

        public FilmeAController(MVCFilmesContext context)
        {
            _context = context;
        }

        // GET: FilmeA
        public async Task<IActionResult> Index(string Texto, string Genero)
        {


          

            // query genero
            IQueryable<string> generos = from m in _context.Filmes
                                         orderby m.Genero
                                         select m.Genero;

            // query filme
            var filmes = from m in _context.Filmes
                         select m;

            // filtro genero
            if(!string.IsNullOrWhiteSpace(Genero))

            {


                filmes = filmes.Where(s => s.Genero == Genero);

            }

            // filtro filme
            if (!string.IsNullOrWhiteSpace(Texto))
            {

                filmes = filmes.Where(s => s.Titulo!.Contains(Texto));

            }




            //ViewModel
            var filmeViewModel = new Models.FilmesViewModel
            {

                Filmes = await filmes.ToListAsync(),
                Generos = new SelectList(await generos.Distinct().ToListAsync())

            };


            return View(filmeViewModel);
                          
        }

        // GET: FilmeA/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Filmes == null)
            {
                return NotFound();
            }

            var filmes = await _context.Filmes
                .FirstOrDefaultAsync(m => m.ID == id);
            if (filmes == null)
            {
                return NotFound();
            }

            return View(filmes);
        }

        // GET: FilmeA/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FilmeA/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Titulo,DataLancamento,Genero,Preco")] Filmes filmes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(filmes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(filmes);
        }

        // GET: FilmeA/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Filmes == null)
            {
                return NotFound();
            }

            var filmes = await _context.Filmes.FindAsync(id);
            if (filmes == null)
            {
                return NotFound();
            }
            return View(filmes);
        }

        // POST: FilmeA/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Titulo,DataLancamento,Genero,Preco,Pontos")] Filmes filmes)
        {
            if (id != filmes.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(filmes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmesExists(filmes.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(filmes);
        }

        // GET: FilmeA/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Filmes == null)
            {
                return NotFound();
            }

            var filmes = await _context.Filmes
                .FirstOrDefaultAsync(m => m.ID == id);
            if (filmes == null)
            {
                return NotFound();
            }

            return View(filmes);
        }

        // POST: FilmeA/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Filmes == null)
            {
                return Problem("Entity set 'MVCFilmesContext.Filmes'  is null.");
            }
            var filmes = await _context.Filmes.FindAsync(id);
            if (filmes != null)
            {
                _context.Filmes.Remove(filmes);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmesExists(int id)
        {
          return (_context.Filmes?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

MVCFilmes/Controllers/FilmesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography.X509Certificates;

using System;
using System.Threading;

namespace MVCFilmes.Controllers
{
    public class FilmesController : Controller
    {
        public IActionResult Index()
        {
            
            return View();
        }
        public IActionResult BemVindo(string nome, int id)
        {
            ViewData["Title"] = "Bem vindos";

            ViewData["Nome"] = nome;
            ViewData["Numerox"] = id;


            return View();
        }




    }

}

MVCFilmes/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCFilmes.Models;
using System.Diagnostics;

namespace MVCFilmes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCFilmes/Views/FilmeA/Create.cshtml
@model MVCFilmes.Models.Filmes

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Filmes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataLancamento" class="control-label"></label>
                <input asp-for="DataLancamento" class="form-control" />
                <span asp-validation-for="DataLancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pontos" class="control-label"></label>
                <input asp-for="Pontos" class="form-control" />
                <span asp-validation-for="Pontos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCFilmes/Views/FilmeA/Delete.cshtml
@model MVCFilmes.Models.Filmes

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Filmes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataLancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pontos)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pontos)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVCFilmes/Views/FilmeA/Details.cshtml
@model MVCFilmes.Models.Filmes

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Filmes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataLancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataLancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pontos)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pontos)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVCFilmes/Views/FilmeA/Edit.cshtml
@model MVCFilmes.Models.Filmes

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Filmes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataLancamento" class="control-label"></label>
                <input asp-for="DataLancamento" class="form-control" />
                <span asp-validation-for="DataLancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pontos" class="control-label"></label>
                <input asp-for="Pontos" class="form-control" />
                <span asp-validation-for="Pontos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCFilmes/Views/FilmeA/Index.cshtml
@model MVCFilmes.Models.FilmesViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Criar novo filme</a>
</p>
<form asp-controller="filmeA" asp-action="Index" method="post">
   <p>
       Titulo: <input type="text"  name="texto"  />

       
        
      Generos: <select asp-for="Genero" asp-items="Model.Generos">
            <option value="">Todos</option>
       </select>

        <input type="submit" value="Buscar" />
       </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Filmes[0].Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Filmes[0].DataLancamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Filmes[0].Genero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Filmes[0].Preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Filmes[0].Pontos)
            </th>
            <th></th>
        </tr> 
    </thead>
    <tbody>
@foreach (var item in Model.Filmes) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataLancamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>
             <td>
                 @Html.DisplayFor(modelItem => item.Pontos)
              </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MVCFilmes/Views/Filmes/BemVindo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



<h1>Bem Vindo</h1>

Olá: @ViewData["Nome"]


@if (ViewData["Numerox"] != null)
{
    <ul> 
@for(int i = 0; i <=  Convert.ToInt32(ViewData["Numerox"]); i++)
{
  <li> @i </li>

}
    </ul>
}



        

MVCFilmes/Views/Filmes/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

    ViewData["Title"] = "Lista de filmes";
}


<h1>Filmes Index </h1>

MVCFilmes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCFilmes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCFilmes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCFilmes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCFilmes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        </li> 

                        <a class="nav-link text-dark" asp-controller="FilmeA"asp-action="Index" >Filmes</a>


                           
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCFilmes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>